-- ============================================================
--  RBAC — tabela ról użytkowników (user_roles) + RLS
--
--  Kontekst: tabela powstała pierwotnie ręcznie w panelu Supabase
--  (SQL Editor), poza migracjami. Ta migracja "cofa ją do kodu",
--  żeby baza i src/lib/database.types.ts były spójne (per CLAUDE.md).
--
--  Migracja jest IDEMPOTENTNA i bezpieczna na remote, gdzie tabela
--  już istnieje (super_admin × 2, brak wierszy 'admin'):
--    - CREATE TABLE IF NOT EXISTS odtwarza ją tylko lokalnie,
--    - sekcja "dostosowanie CHECK" zwęża dozwolone role do
--      ('user','super_admin') również na istniejącej tabeli.
--
--  Kształt wierny produkcji: osobne id (PK) i user_id (UNIQUE FK).
--  Model 1 rola na usera. Rola w UI gatuje trasy (/admin/* tylko
--  super_admin); autoryzacja API nadal przez RLS (per CLAUDE.md).
-- ============================================================

-- ============================================================
-- USER_ROLES (1:1 z auth.users przez user_id)
-- ============================================================

CREATE TABLE IF NOT EXISTS user_roles (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID        NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    role       TEXT        NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT TIMEZONE('utc', NOW())
);

COMMENT ON TABLE  user_roles            IS 'Rola RBAC użytkownika — 1:1 z auth.users przez user_id. Gating tras w UI; API chronione przez RLS.';
COMMENT ON COLUMN user_roles.user_id    IS 'FK do auth.users.id (UNIQUE — jedna rola na usera)';
COMMENT ON COLUMN user_roles.role       IS 'Rola aplikacyjna: user | super_admin (CHECK)';


-- ============================================================
-- DOSTOSOWANIE CHECK — zawężenie ról do (user, super_admin)
-- ============================================================
-- Produkcyjny CHECK dopuszczał ('super_admin','admin','user'). Brak
-- wierszy 'admin' (zweryfikowane), więc zawężenie jest bezpieczne.
-- Dropujemy stary constraint po nazwie z panelu i dokładamy własny,
-- nazwany deterministycznie — całość idempotentna (IF EXISTS / IF NOT).

ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS user_roles_role_check;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.user_roles'::regclass
          AND conname  = 'user_roles_role_allowed'
    ) THEN
        ALTER TABLE user_roles
            ADD CONSTRAINT user_roles_role_allowed
            CHECK (role IN ('user', 'super_admin'));
    END IF;
END
$$;


-- ============================================================
-- HELPER — zwraca rolę zalogowanego usera
-- ============================================================
-- Analogiczny do current_user_company_id() z 0002.
-- STABLE: planner cache'uje per statement. SECURITY DEFINER: omija RLS
-- na user_roles (inaczej polityka odczytująca własną rolę by się
-- rekursywnie zablokowała). search_path explicit — nie do nadpisania.
-- COALESCE: brak wiersza => domyślnie 'user' (fail-closed względem admina).

CREATE OR REPLACE FUNCTION current_user_role()
RETURNS TEXT
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT COALESCE(
        (SELECT role FROM user_roles WHERE user_id = auth.uid()),
        'user'
    )
$$;

REVOKE EXECUTE ON FUNCTION current_user_role() FROM PUBLIC;
GRANT  EXECUTE ON FUNCTION current_user_role() TO authenticated;


-- ============================================================
-- RLS — user_roles
-- ============================================================
-- SELECT tylko własnej roli (front czyta swoją rolę po zalogowaniu).
-- INSERT/UPDATE/DELETE bez polityk => tylko service_role (nadawanie ról
-- offline, jak seeding firm/userów w 0002).

ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_roles_select_self ON user_roles;
CREATE POLICY user_roles_select_self
    ON user_roles
    FOR SELECT
    TO authenticated
    USING (user_id = auth.uid());

GRANT SELECT ON user_roles TO authenticated;
